---
apiVersion: v1
kind: Pod
metadata:
  name: hello
  labels:
    app: hello
spec:
  containers:
    - name: hello-from
      image: pbitty/hello-from:latest
      ports:
        - name: http
          containerPort: 80
