kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  apiServerAddress: 127.0.0.1
  apiServerPort: 6443

nodes:
- role: control-plane
  extraPortMappings:
    - containerPort: 31000
      hostPort: 31000
      protocol: TCP
    - containerPort: 32000
      hostPort: 32000
      protocol: TCP

- role: worker
- role: worker
- role: worker
