---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello-from
        image: pbitty/hello-from:latest
        ports:
          - name: http
            containerPort: 80
